### PR TITLE
Change error-raising behaviour.

### PR DESCRIPTION
**Pull request by omp**
The previous logic was to raise an error whenever FreeImage calls the
error output handler, which is also called for warnings. This change
instead raises an error when a FreeImage function call returns a null
pointer.

### CODE REVIEW

**Comment by zenspider** [comment]
Ugh. Can you point me to changelog or something in freeimage that shows they made that stupid decision?

**Comment by omp** [comment]
This is essentially a fix for issue #21 on here, which references the following freeimage issue:
https://sourceforge.net/p/freeimage/support-requests/31/

> This being said, you can load an image that looks suspicious to FreeImage (you will then get an error message or a warning message that can be catched using FreeImage_SetOutputMessage), but still have a correct dib on output (i.e. a dib that is not NULL). 
> As long as the returned dib is not NULL, then you can trust FreeImage. The fact that you get warning/error messages is not a problem as long as the returned dib is not NULL.

The fix I implemented is to still store the warning/error output in the thread, but only raise it as an error if a null pointer is returned from one of the freeimage function calls, clearing it otherwise.

**Comment by zenspider** [comment]
Merging... but do you happen to have an image that would cause a warning w/o an error?

**Comment by zenspider** [comment]
Merged

**Comment by omp** [comment]
Thanks. Here is one such image: http://i4.ypcdn.com/blob/bd2aef4e8c90f4c2864d2203ccd22719c0b0f6e7

**Pull request closed without merging**
